FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

# Imagem SDK para build da aplicação
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["violaoapi/violaoapi.csproj", "violaoapi/"]
RUN dotnet restore "violaoapi/violaoapi.csproj"
COPY . .
WORKDIR "/violaoapi"
RUN dotnet build "violaoapi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "violaoapi.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "violaoapi.dll"]